// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_cancel_fraction
IntegerVector cpp_cancel_fraction(double numerator, double denominator);
RcppExport SEXP _schoolmath_cpp_cancel_fraction(SEXP numeratorSEXP, SEXP denominatorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type numerator(numeratorSEXP);
    Rcpp::traits::input_parameter< double >::type denominator(denominatorSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cancel_fraction(numerator, denominator));
    return rcpp_result_gen;
END_RCPP
}
// cpp_decimal2fraction
IntegerVector cpp_decimal2fraction(std::string decimal, int period);
RcppExport SEXP _schoolmath_cpp_decimal2fraction(SEXP decimalSEXP, SEXP periodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type decimal(decimalSEXP);
    Rcpp::traits::input_parameter< int >::type period(periodSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_decimal2fraction(decimal, period));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gcd
NumericVector cpp_gcd(double x, double y);
RcppExport SEXP _schoolmath_cpp_gcd(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gcd(x, y));
    return rcpp_result_gen;
END_RCPP
}
// cpp_is_prim
LogicalVector cpp_is_prim(NumericVector x);
RcppExport SEXP _schoolmath_cpp_is_prim(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_is_prim(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_prime_factor
NumericVector cpp_prime_factor(double x);
RcppExport SEXP _schoolmath_cpp_prime_factor(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_prime_factor(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_primes
NumericVector cpp_primes(int start, int end, bool live);
RcppExport SEXP _schoolmath_cpp_primes(SEXP startSEXP, SEXP endSEXP, SEXP liveSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type end(endSEXP);
    Rcpp::traits::input_parameter< bool >::type live(liveSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_primes(start, end, live));
    return rcpp_result_gen;
END_RCPP
}
// cpp_scm
NumericVector cpp_scm(double x, double y);
RcppExport SEXP _schoolmath_cpp_scm(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_scm(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_schoolmath_cpp_cancel_fraction", (DL_FUNC) &_schoolmath_cpp_cancel_fraction, 2},
    {"_schoolmath_cpp_decimal2fraction", (DL_FUNC) &_schoolmath_cpp_decimal2fraction, 2},
    {"_schoolmath_cpp_gcd", (DL_FUNC) &_schoolmath_cpp_gcd, 2},
    {"_schoolmath_cpp_is_prim", (DL_FUNC) &_schoolmath_cpp_is_prim, 1},
    {"_schoolmath_cpp_prime_factor", (DL_FUNC) &_schoolmath_cpp_prime_factor, 1},
    {"_schoolmath_cpp_primes", (DL_FUNC) &_schoolmath_cpp_primes, 3},
    {"_schoolmath_cpp_scm", (DL_FUNC) &_schoolmath_cpp_scm, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_schoolmath(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
