# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_cancel_fraction <- function(numerator, denominator) {
    .Call(`_schoolmath_cpp_cancel_fraction`, numerator, denominator)
}

cpp_decimal2fraction <- function(decimal, period = -1L) {
    .Call(`_schoolmath_cpp_decimal2fraction`, decimal, period)
}

cpp_gcd <- function(x, y) {
    .Call(`_schoolmath_cpp_gcd`, x, y)
}

cpp_is_prim <- function(x) {
    .Call(`_schoolmath_cpp_is_prim`, x)
}

cpp_prime_factor <- function(x) {
    .Call(`_schoolmath_cpp_prime_factor`, x)
}

cpp_primes <- function(start, end, live) {
    .Call(`_schoolmath_cpp_primes`, start, end, live)
}

cpp_scm <- function(x, y) {
    .Call(`_schoolmath_cpp_scm`, x, y)
}

